name: transmirror
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  url_launcher: ^6.3.2
  intl: ^0.20.2
  get_storage: ^2.1.1
  logger: ^2.6.2
  iconsax: ^0.0.8
  # launcher_name: ^1.0.2
  # flutter_launcher_icons: ^0.14.4
  # flutter_native_splash: ^2.4.7
  # rename: ^3.1.0
  google_fonts: ^6.3.2
  # permission_handler: ^12.0.1
  # camera: ^0.11.2+1
  # arkit_plugin: ^1.2.0
  # vector_math: ^2.1.5
  # persistent_bottom_nav_bar_v2: ^6.2.0
  pdf: ^3.11.3
  # http: ^1.2.0
  # flutter_dotenv: ^5.1.0
  # device_preview: ^1.3.1
  lottie: ^3.1.0
  dropdown_textfield: ^1.0.8

  # Firebase dependencies
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  launcher_shortcuts: ^1.1.4
  supertonic_flutter: ^0.1.1
  flutter_tts: ^4.2.5
  google_mlkit_translation: ^0.13.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  flutter_overlay_window: ^0.5.0
  google_mlkit_text_recognition: ^0.15.1
  swipe_image_ocr: ^0.0.1+2
  gal: ^2.3.0
  google_mlkit_language_id: ^0.13.1
  image_picker: ^1.2.1
  device_info_plus: ^12.3.0
  speech_to_text: ^7.3.0
  file_selector: ^1.0.4
  easy_pdf_viewer: ^1.0.7
  docx_file_viewer: ^1.0.1
  # image_gallery_saver: ^2.0.3
  # flutter_overlay_window: ^0.5.0
  # voice_to_text: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/logos/
  - assets/images/
  - assets/animations/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo.png"
